version: '3.8'

services:
  mongo:
    image: mongo:6
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 4MaOhzlcOxyhTib0O6fXE4MaOhTib0O6fNnUBRsHKfCNnUXE
      MONGO_INITDB_DATABASE: email_service
    volumes:
      - mongo_data:/data/db

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    restart: always
    ports:
      - "8085:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: 4MaOhzlcOxyhTib0O6fXE4MaOhTib0O6fNnUBRsHKfCNnUXE
      ME_CONFIG_BASICAUTH_USERNAME: XE4MaOhTib0O6fNnU
      ME_CONFIG_BASICAUTH_PASSWORD: BRsHKfCNnUXE4MaOhzlcOxyhTib0O6f
    depends_on:
      - mongo

volumes:
  mongo_data:
